/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "IVAn",
  "description": "Think Twice,Code Once",
  "base": "/",
  "headTags": [],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/assets/img/favicon.png",
        "heroText": "IVAn`s VuePress Blog",
        "tagline": "talk is cheap,show me the code",
        "actionText": "快速上手 →",
        "actionLink": "/guide/",
        "features": [
          {
            "title": "简洁至上",
            "details": "以 Markdown 为中心的项目结构，以最少的配置帮助你专注于写作。"
          },
          {
            "title": "Vue驱动",
            "details": "享受 Vue + webpack 的开发体验，在 Markdown 中使用 Vue 组件，同时可以使用 Vue 来开发自定义主题。"
          },
          {
            "title": "高性能",
            "details": "VuePress 为每个页面预渲染生成静态的 HTML，同时在页面被加载的时候，将作为 SPA 运行。"
          }
        ],
        "footer": "MIT Licensed | Copyright © 2018-present Evan You"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-15b55480",
      "path": "/"
    },
    {
      "title": "文章列表",
      "frontmatter": {},
      "regularPath": "/front/",
      "relativePath": "front/index.md",
      "key": "v-5763fc87",
      "path": "/front/",
      "headers": [
        {
          "level": 2,
          "title": "文章列表",
          "slug": "文章列表"
        }
      ]
    },
    {
      "title": "This is guide",
      "frontmatter": {},
      "regularPath": "/guide/",
      "relativePath": "guide/README.md",
      "key": "v-3db66813",
      "path": "/guide/",
      "headers": [
        {
          "level": 2,
          "title": "This is guide",
          "slug": "this-is-guide"
        },
        {
          "level": 3,
          "title": "title3",
          "slug": "title3"
        },
        {
          "level": 3,
          "title": "title3-01",
          "slug": "title3-01"
        },
        {
          "level": 2,
          "title": "small title",
          "slug": "small-title"
        }
      ]
    },
    {
      "title": "目的：实现在java后台直接根据options生成Echarts统计图片",
      "frontmatter": {},
      "regularPath": "/java/Java+PhantomJs%E5%AE%9E%E7%8E%B0%E5%90%8E%E5%8F%B0%E7%94%9F%E6%88%90Echarts%E5%9B%BE%E7%89%87.html",
      "relativePath": "java/Java+PhantomJs实现后台生成Echarts图片.md",
      "key": "v-631e94d3",
      "path": "/java/Java+PhantomJs%E5%AE%9E%E7%8E%B0%E5%90%8E%E5%8F%B0%E7%94%9F%E6%88%90Echarts%E5%9B%BE%E7%89%87.html",
      "headers": [
        {
          "level": 3,
          "title": "目的：实现在java后台直接根据options生成Echarts统计图片",
          "slug": "目的-实现在java后台直接根据options生成echarts统计图片"
        },
        {
          "level": 3,
          "title": "本文实现原理：java调用Runtime.getRuntime().exec()的方式调用phantomjs。然后由phantomjs处理echarts数据,最终生成图片。",
          "slug": "本文实现原理-java调用runtime-getruntime-exec-的方式调用phantomjs。然后由phantomjs处理echarts数据-最终生成图片。"
        },
        {
          "level": 2,
          "title": "第一步：下载并安装PhantomJs",
          "slug": "第一步-下载并安装phantomjs"
        },
        {
          "level": 3,
          "title": "下载地址： http://phantomjs.org/download.html",
          "slug": "下载地址-http-phantomjs-org-download-html"
        },
        {
          "level": 3,
          "title": "下载完成后配置环境变量",
          "slug": "下载完成后配置环境变量"
        },
        {
          "level": 3,
          "title": "验证结果",
          "slug": "验证结果"
        },
        {
          "level": 2,
          "title": "第二步：准备生成图片相关的脚本：",
          "slug": "第二步-准备生成图片相关的脚本"
        },
        {
          "level": 3,
          "title": "jquery-3.2.1.min.js  ​ 下载任意jquery.js版本即可",
          "slug": "jquery-3-2-1-min-js-​-下载任意jquery-js版本即可"
        },
        {
          "level": 3,
          "title": "下载地址: JQuery官网下载",
          "slug": "下载地址-jquery官网下载"
        },
        {
          "level": 3,
          "title": "echarts.min.js  ​ 下载任意jquery.js版本即可",
          "slug": "echarts-min-js-​-下载任意jquery-js版本即可"
        },
        {
          "level": 3,
          "title": "下载地址: ECharts官网下载",
          "slug": "下载地址-echarts官网下载"
        },
        {
          "level": 3,
          "title": "echarts-convert.js",
          "slug": "echarts-convert-js"
        },
        {
          "level": 3,
          "title": "此脚本为最主要脚本，生成echart图片的主要逻辑代码都在此脚本内。（完整源码如下）",
          "slug": "此脚本为最主要脚本-生成echart图片的主要逻辑代码都在此脚本内。-完整源码如下"
        },
        {
          "level": 2,
          "title": "第三步：后端准备及代码编写",
          "slug": "第三步-后端准备及代码编写"
        },
        {
          "level": 3,
          "title": "自己编写常用的测试options，主要为折线图、柱状图、饼图",
          "slug": "自己编写常用的测试options-主要为折线图、柱状图、饼图"
        },
        {
          "level": 3,
          "title": "这里推荐一个Java生成option的插件 ---- ECharts - Java类库 Gitee地址",
          "slug": "这里推荐一个java生成option的插件-echarts-java类库-gitee地址"
        },
        {
          "level": 3,
          "title": "使用Java传cmd命令调用 PhantomJS 生成 echarts 图片（完整源码如下）",
          "slug": "使用java传cmd命令调用-phantomjs-生成-echarts-图片-完整源码如下"
        },
        {
          "level": 3,
          "title": "生成的图片输出到了上述代码中定义的文件夹内，结果如图",
          "slug": "生成的图片输出到了上述代码中定义的文件夹内-结果如图"
        }
      ]
    },
    {
      "title": "Java 操作Word、Excel的几种方法",
      "frontmatter": {},
      "regularPath": "/java/Java%E4%BD%BF%E7%94%A8poi-tl%E6%93%8D%E4%BD%9Cword%E6%96%87%E6%A1%A3.html",
      "relativePath": "java/Java使用poi-tl操作word文档.md",
      "key": "v-84967c6a",
      "path": "/java/Java%E4%BD%BF%E7%94%A8poi-tl%E6%93%8D%E4%BD%9Cword%E6%96%87%E6%A1%A3.html",
      "headers": [
        {
          "level": 2,
          "title": "Java 操作Word、Excel的几种方法",
          "slug": "java-操作word、excel的几种方法"
        },
        {
          "level": 2,
          "title": "Poi-tl 文档地址",
          "slug": "poi-tl-文档地址"
        }
      ]
    },
    {
      "title": "Java处理emoji的方式",
      "frontmatter": {},
      "regularPath": "/java/java%E5%A4%84%E7%90%86emoji%E7%9A%84%E6%96%B9%E5%BC%8F.html",
      "relativePath": "java/java处理emoji的方式.md",
      "key": "v-aa994232",
      "path": "/java/java%E5%A4%84%E7%90%86emoji%E7%9A%84%E6%96%B9%E5%BC%8F.html",
      "headers": [
        {
          "level": 2,
          "title": "问题由来: java后端获取微信小程序用户昵称含emoji时,显示乱码。",
          "slug": "问题由来-java后端获取微信小程序用户昵称含emoji时-显示乱码。"
        },
        {
          "level": 2,
          "title": "处理思路",
          "slug": "处理思路"
        }
      ]
    },
    {
      "title": "文章列表",
      "frontmatter": {},
      "regularPath": "/java/",
      "relativePath": "java/index.md",
      "key": "v-4c17a423",
      "path": "/java/",
      "headers": [
        {
          "level": 2,
          "title": "文章列表",
          "slug": "文章列表"
        }
      ]
    },
    {
      "title": "基于Java的TCP Socket通信详解",
      "frontmatter": {},
      "regularPath": "/java/%E5%9F%BA%E4%BA%8EJava%E7%9A%84TCPSocket%E9%80%9A%E4%BF%A1%E8%AF%A6%E8%A7%A3.html",
      "relativePath": "java/基于Java的TCPSocket通信详解.md",
      "key": "v-acbeb42e",
      "path": "/java/%E5%9F%BA%E4%BA%8EJava%E7%9A%84TCPSocket%E9%80%9A%E4%BF%A1%E8%AF%A6%E8%A7%A3.html",
      "headers": [
        {
          "level": 2,
          "title": "TCP Socket通信是一种比较常用的基于连接的网络通信方式。本文通过Java实现TCP Socket通信，并将其用于计算机端,Android手机端,硬件设备端,同时做到代码规范化，实现代码最大化复用。",
          "slug": "tcp-socket通信是一种比较常用的基于连接的网络通信方式。本文通过java实现tcp-socket通信-并将其用于计算机端-android手机端-硬件设备端-同时做到代码规范化-实现代码最大化复用。"
        },
        {
          "level": 3,
          "title": "| 本文代码可在GitHub下载，建议对照源码阅读文章 https://github.com/IVanMissAya/tcp_server",
          "slug": "本文代码可在github下载-建议对照源码阅读文章-https-github-com-ivanmissaya-tcp-server"
        },
        {
          "level": 2,
          "title": "连接的建立过程",
          "slug": "连接的建立过程"
        },
        {
          "level": 2,
          "title": "SocketTransceiver的实现",
          "slug": "sockettransceiver的实现"
        },
        {
          "level": 2,
          "title": "TcpServer的实现",
          "slug": "tcpserver的实现"
        },
        {
          "level": 2,
          "title": "TcpClient的实现",
          "slug": "tcpclient的实现"
        },
        {
          "level": 3,
          "title": "另附 windows 下tcp 测试工具",
          "slug": "另附-windows-下tcp-测试工具"
        }
      ]
    }
  ],
  "themeConfig": {
    "nav": [
      {
        "text": "主页",
        "link": "/"
      },
      {
        "text": "前端",
        "link": "/front/index.md"
      },
      {
        "text": "后端(Java)",
        "link": "/java/index.md"
      },
      {
        "text": "工具",
        "items": [
          {
            "text": "java基础",
            "link": "/java/java-base/"
          },
          {
            "text": "java与opc通信",
            "link": "/java/java-opc/"
          }
        ]
      },
      {
        "text": "我的小站",
        "link": "https://www.ivan.fun"
      }
    ],
    "displayAllHeaders": true,
    "activeHeaderLinks": false,
    "logo": "/assets/img/favicon.png",
    "sidebarDepth": 2,
    "sidebar": {
      "/life/": [
        {
          "title": "生活测试",
          "collapsable": false,
          "children": [
            {
              "title": "生活测试01",
              "path": "/life/life01"
            },
            {
              "title": "生活测试02",
              "path": "/life/life02"
            },
            {
              "title": "生活测试03",
              "path": "/life/life03"
            }
          ]
        }
      ],
      "/study/english/": [
        {
          "title": "英语",
          "collapsable": false,
          "children": [
            {
              "title": "第一节",
              "path": "/study/english/english01"
            },
            {
              "title": "第二节",
              "path": "/study/english/english02"
            },
            {
              "title": "第三节",
              "path": "/study/english/english03"
            }
          ]
        }
      ],
      "/study/math/": [
        {
          "title": "数学",
          "collapsable": false,
          "children": [
            {
              "title": "第一节",
              "path": "/study/math/math01"
            },
            {
              "title": "第二节",
              "path": "/study/math/math02"
            },
            {
              "title": "第三节",
              "path": "/study/math/math03"
            }
          ]
        }
      ]
    },
    "lastUpdated": "Last Updated",
    "nextLinks": true,
    "prevLinks": true,
    "smoothScroll": true
  }
}